StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{66F75C45A9D68C92}" {
   Id "SFW_Spawnpoint1"
   Target_en_us "Forward Operating Base"
   Target_fr_fr "Base d'opérations avancée"
   Target_it_it "Base operativa avanzata"
   Target_de_de "Vorwärtsoperationsbasis"
   ActorGender MALE
   Modified 1727489457
   Author "Blackheart_Six"
   LastChanged "Blackheart_Six"
  }
  CustomStringTableItem "{66F75C42B4C62D12}" {
   Id "SFW_Spawnpoint2"
   Modified 1727489179
   Author "Blackheart_Six"
   LastChanged "Blackheart_Six"
  }
  CustomStringTableItem "{66F75C42B70853BA}" {
   Id "SFW_Spawnpoint3"
   Modified 1727489182
   Author "Blackheart_Six"
   LastChanged "Blackheart_Six"
  }
 }
}